server:
  port: 8081

spring:
  application:
    name: Auth-Service

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: mysecretkeyghfhsrfrliueoiriflhlisduhgedufhgdshgsiod
  expiration: 864000